/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2022-04-24 07:00:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Registration</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: tomato;\">\r\n");
      out.write("<center>\r\n");
      out.write("\t<h1>Registration Process of Bank of Jspider !</h1>\r\n");
      out.write("\t<form action=\"RegistrationController\" method=\"post\">\r\n");
      out.write("\t<label>First Name</label>\r\n");
      out.write("\t<input name=\"fn\"></input>\r\n");
      out.write("\t<br></br>\r\n");
      out.write("\t<label>Last Name</label>\r\n");
      out.write("\t<input name=\"fn\"></input>\r\n");
      out.write("\t<br></br>\r\n");
      out.write("\t<label>Mobile</label>\r\n");
      out.write("\t<input name=\"mob\"></input>\r\n");
      out.write("\t<br></br>\t\r\n");
      out.write("\t<label>Aadhar Card No:</label>\r\n");
      out.write("\t<input name=\"aadhar\"></input>\r\n");
      out.write("\t<br></br>\r\n");
      out.write("\t<label>Pan Card</label>\r\n");
      out.write("\t<input name=\"pancard\"></input>\r\n");
      out.write("\t<br></br>\r\n");
      out.write("\t<label>Email - ID</label>\r\n");
      out.write("\t<input type=\"email\" name=\"email\"></input>\r\n");
      out.write("\t<br></br>\r\n");
      out.write("\t<label>Address</label>\r\n");
      out.write("\t<textarea name=\"addr\"></textarea>\r\n");
      out.write("\t<br></br>\r\n");
      out.write("\t<label>Date of Birth</label>\r\n");
      out.write("\t<input type=\"date\" name=\"dob\">\r\n");
      out.write("\t<br></br>\r\n");
      out.write("\t<label>Gender : </label>\r\n");
      out.write("\t<input type=\"radio\" name=\"abc\">Male</input>\r\n");
      out.write("\t<input type=\"radio\" name=\"abc\">Female</input>\r\n");
      out.write("\t<br></br>\r\n");
      out.write("\t<label>Type of Account </label>\r\n");
      out.write("\t<input type=\"radio\" name=\"type\">SB</input>\r\n");
      out.write("\t<input type=\"radio\" name=\"type\">FD</input>\r\n");
      out.write("\t<input type=\"radio\" name=\"type\">CA</input>\r\n");
      out.write("\t<input type=\"radio\" name=\"type\">RD</input>\r\n");
      out.write("\t<br></br>\t\r\n");
      out.write("\t<label>Amount : </label>\r\n");
      out.write("\t<input placeholder=\".rs\" name=\"amt\"></input>\r\n");
      out.write("\t<br></br>\r\n");
      out.write("\t<label>Password : </label>\r\n");
      out.write("\t<input type=\"password\" name=\"pwd\"></input>\r\n");
      out.write("\t<br></br>\r\n");
      out.write("\t<label>Confirm Password : </label>\r\n");
      out.write("\t<input type=\"password\"></input>\r\n");
      out.write("\t<br></br>\r\n");
      out.write("\t<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("\t<input type=\"reset\" value=\"Reset\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<a href=\"Login.jsp\">Already registered ? Login</a>\r\n");
      out.write("\t\r\n");
      out.write("</center>\r\n");

String errormsg = (String)request.getAttribute("msg");
if(errormsg != null){
	
      out.write("\r\n");
      out.write("\t<h1 style=\"color: red;\">");
      out.print( errormsg );
      out.write("</h1>\r\n");
      out.write("\t");

}

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
